#%RAML 1.0
title: american-twitch-flights-api

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
  post:

  /{ID}:
    get:
    